from time import sleep
from userbot.events import register


@register(outgoing=True, pattern='^.a(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Hai Perkenalkan Namaku Abe🙈`")
    sleep(3)
    await typew.edit("`16 Tahun Otw 17😎`")
    sleep(2)
    await typew.edit("`Tinggal Di Kaltim`")
    sleep(2)
    await typew.edit("`Salam Kenal Yaa 😉🤗`")
    await typew.edit("`🙈😝🙉🤪🤭😜🤗`")
    sleep(0.1)
    await typew.edit("`🤗😜🤭🙈😝🤪🙉`")
    sleep(0.1)
    await typew.edit("`🤪🙉😝🤗🙈🤭😜`")
    sleep(0.1)
    await typew.edit("`😚😊😘😉😎🤗😁`")
    sleep(0.1)
    await typew.edit("`😊😎😁😘🤗😚😉`")
    sleep(0.1)
    await typew.edit("`🤗😚😉😎😘☺️😁`")
    sleep(0.1)
    await typew.edit("`😉🤗😊😁😚😘😎`")
    sleep(0.1)
    await typew.edit("`😎😁😚😊🤗😉😘`")
    sleep(0.1)
    await typew.edit("`🙉🤗😜🤗🙈😝🤭`")
    sleep(0.1)
    await typew.edit("`🤭🤪🙉😝🤗😜🙈`")
    sleep(0.1)
    await typew.edit("`😜🙈🤭😝🤪🙉🤗`")
    sleep(0.1)
    await typew.edit("`🙈😝🙉🤪🤭😜🤗`")
# Create by Abe @yangmutebabi

@register(outgoing=True, pattern='^.nana(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Hai Para Kontol dan Memek`")
    sleep(3)
    await typew.edit("`Perkenalkan Saya Angell cantikkkk`")
    sleep(2)
    await typew.edit("`Umur 17 Tahun (Masih Bocil)`")
    sleep(2)
    await typew.edit("`Suka Sange Dadakan🤤`")
    sleep(2)
    await typew.edit("`Suka pap kontol estetik🙈`")
    sleep(2)
    await typew.edit("`Malam suka Open🤫😜`")
    sleep(2)
    await typew.edit("`Siang suka sange, kl suka kamu gdl🤪`")
# Create by Abe @yangmutebabi


@register(outgoing=True, pattern='^.lala(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`𝗛𝗲𝗹𝗹𝗼 𝗞𝗮𝗸𝗮𝗸 𝗗𝗮𝗻 𝗔𝗱𝗶𝗸𝟮🙉`")
    sleep(3)
    await typew.edit("`Kenalin Aku Lolinya @yangmutebabi 😜`")
    sleep(3)
    await typew.edit("`Nama Saya Lala🤗`")
    sleep(2)
    await typew.edit("`Asalnya Kebumian Loli Xixixi🙈`")
    sleep(2)
    await typew.edit("`Umurnya Rahasia Dong 😆😝`")
    sleep(2)
    await typew.edit("`Btw Salam Kenal yaa🤭`")
    sleep(2)
    await typew.edit("`🙈😝🙉🤪🤭😜🤗`")
    sleep(0.1)
    await typew.edit("`🤗😜🤭🙈😝🤪🙉`")
    sleep(0.1)
    await typew.edit("`🤪🙉😝🤗🙈🤭😜`")
    sleep(0.1)
    await typew.edit("`😝🤭🙈🤪😜🤗🙉`")
    sleep(0.1)
    await typew.edit("`🙉🤗😜🤗🙈😝🤭`")
    sleep(0.1)
    await typew.edit("`🤭🤪🙉😝🤗😜🙈`")
    sleep(0.1)
    await typew.edit("`😜🙈🤭😝🤪🙉🤗`")
    sleep(0.1)
    await typew.edit("`🙈😝🙉🤪🤭😜🤗`")
#Create By Abe @yangmutebabi



@register(outgoing=True, pattern='^.matt(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**Maitreya Ganteng☑️**")
    sleep(0.2)
    await typew.edit("**Maitreya Ganteng✅**")
    sleep(2)
    await typew.edit("**Ganteng Maksimal☑️**")
    sleep(0.2)
    await typew.edit("**Ganteng Maksimal✅**")
    sleep(2)
    await typew.edit("**Suka Coli☑️**")
    sleep(1)
    await typew.edit("**Colikiawan✅**")
    sleep(2)
    await typew.edit("**Anak Tuhan☑️**")
    sleep(1.5)
    await typew.edit("**Puji Tuhan Sangean✅**")
    sleep(2)
    await typew.edit("**Semua Cewek Kayak Babii☑️**")
    sleep(0.2)
    await typew.edit("**Semua Cewek Kayak Babiii✅**")
    sleep(2)
# Create by Abe(@yangmutebabi)



@register(outgoing=True, pattern='^.sayang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(3)
    await typew.edit("`Cuma Mau Bilang`")
    sleep(3)
    await typew.edit("`Aku Sayang Kamu`")
    sleep(1)
    await typew.edit("`I LOVE YOU 💞`")
# Create by myself @localheart


@register(outgoing=True, pattern='^.semangat(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(3)
    await typew.edit("`Apapun Yang Terjadi`")
    sleep(3)
    await typew.edit("`Tetaplah Bernapas`")
    sleep(1)
    await typew.edit("`Dan Selalu Bersyukur`")
# Create by myself @localheart
